import type { PracticeStory } from '@/lib/literacy/samples';

/** Practice stories: Writing (see samples.ts). Evergreen, fact-checked, hand-written at both levels. */
export const WRITING_PRACTICE: readonly PracticeStory[] = [
  {
    slug: 'practice-libraries-lend-more',
    category: 'writing',
    title: 'Libraries lend more than books',
    excerpt:
      'Many public libraries now lend far more than books, from drills and sewing machines to board games, telescopes and seeds. This practice story explores how a “library of things” works and why librarians see it as part of their purpose.',
    publishedAt: '2026-01-05T09:00:00.000Z',
    content: {
      keyIdea: 'Many libraries now lend tools, instruments, telescopes and seeds as well as books, so communities can share useful things instead of each buying their own.',
      levels: {
        '7-8': {
          title: 'Libraries lend more than books',
          paragraphs: [
            'When you think of a library, you probably picture shelves of books. But many public libraries now lend much more than that. In some towns, you can borrow a drill, a sewing machine, a ukulele or a board game with the same card you use for novels.',
            'Some libraries call this a “library of things.” The idea is simple. Lots of useful objects sit unused in cupboards for most of their lives. If a library owns one and lends it out, a whole community can share it. Each family does not need to buy its own.',
            'A few libraries even lend telescopes, so families can explore the night sky before deciding whether to buy one. Others run seed libraries. People take seeds home, grow fruit, vegetables or flowers, and later bring back seeds from their own plants for others to use.',
            'Librarians say these collections fit what libraries have always done. Their purpose is to give everyone access to knowledge and useful resources, whatever they can afford. A book and a telescope can both help people learn something new. Sharing them also means fewer things are made and thrown away, which is good for the planet.',
          ],
        },
        '9-10': {
          title: 'Why libraries are lending tools, telescopes and seeds',
          paragraphs: [
            'Walk into a public library today and you may find more than rows of books. Alongside novels and reference guides, many libraries now lend drills, sewing machines, musical instruments, board games and even telescopes, all borrowed with an ordinary library card.',
            'Collections like these are often called “libraries of things,” and the reasoning behind them is straightforward. Plenty of useful objects spend most of their lives unused in cupboards and garages; a drill, for example, may be switched on for only a few minutes a year. When a library owns one and lends it out, a single item can serve an entire community, and households avoid paying for something they would use only occasionally.',
            'Some libraries have extended the idea to living things. At a seed library, members take home seeds, grow fruit, vegetables or flowers, and then return seeds collected from their own plants, so the collection renews itself each season. Telescope loans, meanwhile, let families explore the night sky before deciding whether such an expensive purchase would be worthwhile.',
            'Librarians argue that these collections are not a departure from their mission but an extension of it. Libraries exist to give everyone access to knowledge and resources, regardless of what they can afford, and a telescope can teach as much as a textbook. There is an environmental benefit, too: when objects are shared, fewer need to be manufactured, and fewer end up as waste. For many people, the humble library card has quietly become one of the most useful things in their wallet.',
          ],
        },
      },
      vocabulary: [
        { word: 'community', partOfSpeech: 'noun', definition: 'A group of people who live in the same area or share something', example: 'Our whole community turned up to clean the beach after the storm.', band: 'both' },
        { word: 'explore', partOfSpeech: 'verb', definition: 'To look around something carefully to learn about it', example: 'On the first day of camp we explored the woods behind the cabins.', band: 'both' },
        { word: 'access', partOfSpeech: 'noun', definition: 'The chance or right to use or reach something', example: 'Every student has access to the computer room at lunchtime.', band: 'both' },
        { word: 'resources', partOfSpeech: 'noun', definition: 'Useful things such as money, materials, tools or information', example: 'The club shares its resources, so nobody has to buy their own paints.', band: 'both' },
        { word: 'afford', partOfSpeech: 'verb', definition: 'To have enough money to pay for something', example: 'We saved our pocket money until we could afford the concert tickets.', band: 'both' },
        { word: 'purpose', partOfSpeech: 'noun', definition: 'The reason something exists or is done', example: 'The purpose of the fire drill is to practise leaving the building safely.', band: '7-8' },
        { word: 'worthwhile', partOfSpeech: 'adjective', definition: 'Worth the time, money or effort', example: 'The long walk was worthwhile because the view from the top was amazing.', band: '9-10' },
      ],
      quiz: [
        {
          id: 'q1',
          skill: 'main-idea',
          question: 'What is the main idea of the story?',
          choices: [
            'Libraries are replacing all of their books with tools and games',
            'Many libraries now lend useful objects as well as books, so people can share them',
            'Telescopes are the most popular thing that libraries lend',
            'People have to pay a fee to borrow tools from a library',
          ],
          answerIndex: 1,
          explanation: 'The story describes libraries lending tools, instruments, games, telescopes and seeds alongside books, so that “a whole community can share” them.',
        },
        {
          id: 'q2',
          skill: 'detail',
          question: 'What do people bring back to a seed library?',
          choices: ['The flowers they picked', 'A report on how their plants grew', 'Money to buy new seeds', 'Seeds from the plants they grew'],
          answerIndex: 3,
          explanation: 'The story says people “later bring back seeds from their own plants for others to use.”',
        },
        {
          id: 'q3',
          skill: 'inference',
          question: 'Why might a family borrow a telescope before buying one?',
          choices: [
            'To find out whether they enjoy looking at the stars enough to spend money on it',
            'Because libraries do not allow people to buy telescopes',
            'Because telescopes from shops do not work at night',
            'To practise mending broken telescopes',
          ],
          answerIndex: 0,
          explanation: 'Families can explore the night sky “before deciding whether to buy one,” which suggests they want to test their interest first.',
        },
        {
          id: 'q4',
          skill: 'vocabulary',
          question: 'Libraries give everyone “access” to knowledge. What does “access” mean here?',
          choices: ['A door into a building', 'A password for a computer', 'The chance or right to use something', 'A list of library rules'],
          answerIndex: 2,
          explanation: 'Libraries let everyone use knowledge and resources, “whatever they can afford,” so access means the chance to use them.',
        },
        {
          id: 'q5',
          skill: 'purpose',
          question: 'Why does the writer mention that sharing means fewer things are made and thrown away?',
          choices: [
            'To warn readers that library items break easily',
            'To explain how libraries choose which books to buy',
            'To persuade readers to stop buying books',
            'To show another benefit of lending objects, beyond saving people money',
          ],
          answerIndex: 3,
          explanation: 'The last paragraph adds a second benefit: sharing objects is “good for the planet,” not just for people’s budgets.',
        },
      ],
      writingPrompts: [
        {
          id: 'p1',
          kind: 'summary',
          prompt: 'Summarise how a “library of things” works in three or four sentences, for someone who has never heard of one.',
          minWords: 40,
          maxWords: 90,
          tips: ['Start by explaining what people can borrow.', 'Say why sharing objects helps people.', 'Use your own words rather than the story’s.'],
        },
        {
          id: 'p2',
          kind: 'opinion',
          prompt: 'If your local library could lend one new kind of object, what should it be? Give your opinion and two reasons.',
          minWords: 60,
          maxWords: 150,
          tips: ['Name the object in your first sentence.', 'Give each reason its own sentence, using “because”.', 'Think about who in your community would use it.'],
        },
        {
          id: 'p3',
          kind: 'letter',
          prompt: 'Write a short letter to a librarian suggesting one way the library could tell more people about the things it lends.',
          minWords: 60,
          maxWords: 150,
          tips: ['Start with a polite greeting.', 'Explain your idea clearly and say who it would reach.', 'Use one word from the vocabulary list.'],
        },
      ],
      discussion: [
        'What is something you own that you use only once in a while? Would you be happy to share it? Why or why not?',
        'Should libraries keep adding new kinds of things to lend, or should they focus on books?',
      ],
    },
  },
  {
    slug: 'practice-how-words-join-the-dictionary',
    category: 'writing',
    title: 'How a new word gets into the dictionary',
    excerpt:
      'Every year dictionaries add hundreds of new words and meanings. This practice story explains how lexicographers track the way people really use language, and why a word needs many users, staying power and a clear meaning before it earns an entry.',
    publishedAt: '2026-01-06T09:00:00.000Z',
    content: {
      keyIdea: 'Dictionaries add a new word when evidence shows that many people use it, over time, with a clear meaning, because dictionaries describe language rather than decide it.',
      levels: {
        '7-8': {
          title: 'How a new word gets into the dictionary',
          paragraphs: [
            'Every year, dictionaries add hundreds of new words. So who decides which words make the cut? The answer might surprise you. It is not a committee of experts voting for their favourite words. In a way, it is all of us.',
            'People who write dictionaries are called lexicographers. Their job is to track how people really use language. They search huge collections of writing, such as books, newspapers, magazines and websites. When a new word starts to appear, they keep a close eye on it.',
            'A word usually needs to pass a few tests. Many different people must use it, not just one group of friends. It has to keep turning up over time instead of vanishing after a few weeks. And people need to use it with a clear, shared meaning.',
            'Some words move fast. In 2013, Oxford Dictionaries chose “selfie” as its Word of the Year, soon after the word became popular. But dictionaries do not tell people how they should speak. They describe how people already speak. So every time you use a word, you add a tiny piece of evidence to the record of the language.',
          ],
        },
        '9-10': {
          title: 'Who decides when a new word is real?',
          paragraphs: [
            'Every year, major dictionaries add hundreds of new words and meanings, and every year someone asks the same question: who decides? The answer is less mysterious, and more open, than many people assume. No panel of experts votes on which words deserve to exist; instead, the decision rests on evidence gathered from millions of ordinary speakers and writers.',
            'The people who compile dictionaries, known as lexicographers, study language as it is actually used. They search vast digital collections of text, called corpora, which include books, newspapers, magazines, transcripts and websites. When an unfamiliar word begins to surface, they monitor how often it appears, who is using it and in which contexts.',
            'To earn an entry, a word generally has to meet several criteria. It must be used widely, by many different people rather than a single small group; it must persist over time instead of fading after a brief burst of popularity; and it must carry a consistent meaning that readers can recognise. Some words clear these hurdles remarkably quickly: in 2013, Oxford Dictionaries named “selfie” its Word of the Year, shortly after the word had spread around the world.',
            'Crucially, modern dictionaries describe language rather than dictate it. They record how people speak and write, not how someone thinks they ought to. The largest dictionaries rarely delete words at all; they simply label older ones as dated or archaic. In that sense, every conversation and message adds a little evidence to the record of the language.',
          ],
        },
      },
      vocabulary: [
        { word: 'evidence', partOfSpeech: 'noun', definition: 'Facts or signs that show something is true', example: 'The empty biscuit tin was evidence that someone had found the snacks.', band: 'both' },
        { word: 'describe', partOfSpeech: 'verb', definition: 'To say what something or someone is like', example: 'Can you describe the new classroom to someone who has not seen it?', band: 'both' },
        { word: 'record', partOfSpeech: 'noun', definition: 'A written account of something that is kept so people can look at it later', example: 'My grandad keeps a record of every bird he sees in the garden.', band: 'both' },
        { word: 'track', partOfSpeech: 'verb', definition: 'To follow and watch something closely over time', example: 'I use an app to track how many pages I read each day.', band: '7-8' },
        { word: 'appear', partOfSpeech: 'verb', definition: 'To start to be seen or to exist', example: 'The first flowers appear in the park at the end of winter.', band: '7-8' },
        { word: 'criteria', partOfSpeech: 'noun', definition: 'The standards used to judge or decide something', example: 'The judges explained their criteria before the art competition began.', band: '9-10' },
        { word: 'persist', partOfSpeech: 'verb', definition: 'To keep going or keep happening', example: 'If the pain persists, you should see a doctor.', band: '9-10' },
        { word: 'consistent', partOfSpeech: 'adjective', definition: 'Staying the same each time', example: 'Her times in the pool have been consistent all season.', band: '9-10' },
      ],
      quiz: [
        {
          id: 'q1',
          skill: 'main-idea',
          question: 'Which sentence best sums up the story?',
          choices: [
            'A panel of experts votes each year on the best new words',
            'Dictionaries tell people which words they are allowed to use',
            'Words join the dictionary when evidence shows many people use them over time',
            'Only words that become popular very quickly are added',
          ],
          answerIndex: 2,
          explanation: 'The story explains that lexicographers add words that many different people keep using, over time, with a shared meaning.',
        },
        {
          id: 'q2',
          skill: 'detail',
          question: 'According to the story, where do lexicographers search for new words?',
          choices: [
            'In huge collections of writing such as books, newspapers and websites',
            'Only in older dictionaries from other countries',
            'In letters that the public sends to them',
            'In spelling lists made by schools',
          ],
          answerIndex: 0,
          explanation: 'The story says they “search huge collections of writing, such as books, newspapers, magazines and websites.”',
        },
        {
          id: 'q3',
          skill: 'inference',
          question: 'Five friends invent a word and use it for one week. Based on the story, is it likely to be added to the dictionary?',
          choices: [
            'Yes, because any word that is used becomes real',
            'No, because it is not used by many different people over time',
            'Yes, if the friends write to a dictionary',
            'No, because dictionaries never add new words',
          ],
          answerIndex: 1,
          explanation: 'A word must be used by “many different people … not just one group of friends” and keep turning up over time.',
        },
        {
          id: 'q4',
          skill: 'vocabulary',
          question: 'Lexicographers “track” how people use language. What does “track” mean here?',
          choices: ['A path for running races', 'Follow and watch closely over time', 'Leave marks on the ground', 'Record a song in a studio'],
          answerIndex: 1,
          explanation: 'Lexicographers keep watching how words are used, which is what “track” means in this sentence.',
        },
        {
          id: 'q5',
          skill: 'purpose',
          question: 'Why does the writer mention the word “selfie”?',
          choices: [
            'To show that dictionaries only add words about phones',
            'To prove that dictionaries dislike new words',
            'To explain how to take a good photo of yourself',
            'To give an example of a word that entered the dictionary quickly',
          ],
          answerIndex: 3,
          explanation: 'The story says “some words move fast” and uses “selfie” as an example of a word that was recognised soon after it became popular.',
        },
      ],
      writingPrompts: [
        {
          id: 'p1',
          kind: 'summary',
          prompt: 'Summarise, in three or four sentences, how a word earns a place in the dictionary.',
          minWords: 40,
          maxWords: 90,
          tips: ['Explain who decides.', 'Include the tests a word has to pass.', 'Finish with the idea that dictionaries describe language.'],
        },
        {
          id: 'p2',
          kind: 'creative',
          prompt: 'Invent a word that you think the world needs. Give its definition, use it in two example sentences and explain how it might spread.',
          minWords: 80,
          maxWords: 200,
          tips: ['Make the meaning clear and specific.', 'Write example sentences that show the meaning.', 'Think about who would start using it first.'],
        },
        {
          id: 'p3',
          kind: 'opinion',
          prompt: 'Should dictionaries add words as soon as they become popular, or wait to see whether they last? Explain your view.',
          minWords: 60,
          maxWords: 150,
          tips: ['State your view in the first sentence.', 'Use one detail from the story as evidence.', 'Mention what someone who disagrees might say.'],
        },
      ],
      discussion: [
        'Which word do you use with friends that older people might not know? How did you learn it?',
        'Why might it matter that dictionaries describe language instead of deciding the rules?',
      ],
    },
  },
  {
    slug: 'practice-where-writers-write',
    category: 'writing',
    title: 'Sheds, hotel rooms and bedrooms: where writers write',
    excerpt:
      'Roald Dahl wrote in a hut at the bottom of his garden, Maya Angelou rented a hotel room, and Emily Dickinson worked at a small table in her bedroom. This practice story looks at the places and routines famous writers chose.',
    publishedAt: '2026-01-07T09:00:00.000Z',
    content: {
      keyIdea: 'Three famous writers worked in very different places, but each built a habit of returning to the same spot, which helped them concentrate and begin.',
      levels: {
        '7-8': {
          title: 'Sheds, hotel rooms and bedrooms: where writers write',
          paragraphs: [
            'Where do you do your best thinking? For many famous writers, the place where they wrote mattered a lot. Some of them chose places that might surprise you.',
            'The children’s author Roald Dahl wrote in a small hut at the bottom of his garden in England. He sat in an old armchair with a writing board across his lap. He wrote in pencil on yellow paper, and he kept the hut exactly the way he liked it. The inside of the hut can now be seen at a museum about his life.',
            'The American poet and author Maya Angelou took a different approach. She rented a hotel room in her home town and arrived early in the morning to write. She asked for the pictures to be taken off the walls, so that nothing would distract her. She brought a dictionary, a Bible and a deck of cards.',
            'The poet Emily Dickinson wrote many of her poems at a small table in her bedroom in Amherst, Massachusetts. Only a handful of her poems were published while she was alive. Today she is seen as one of America’s great poets.',
            'These writers each had a very different routine. What they shared was a habit of going back to the same place to work, day after day.',
          ],
        },
        '9-10': {
          title: 'A hut, a hotel room and a tiny desk: the places writers choose',
          paragraphs: [
            'Ask a writer where they work best and you may get a surprising answer. For many celebrated authors, the setting was not a minor detail but an essential part of the process, carefully arranged to protect their concentration.',
            'Roald Dahl, the author of books such as Matilda and Charlie and the Chocolate Factory, wrote in a modest hut at the bottom of his garden in England. Settled in an old armchair with a writing board across his lap, he worked in pencil on yellow paper, and he kept the cluttered space exactly as he wanted it. The interior of the hut is now preserved at a museum dedicated to his life and work.',
            'Maya Angelou, the American poet and memoirist, followed a very different routine. She rented a hotel room in her home town and arrived early each morning, having asked for every picture to be removed from the walls so that nothing would distract her. With only a dictionary, a Bible and a deck of cards for company, she wrote until around lunchtime.',
            'Emily Dickinson, by contrast, rarely needed to leave home. She composed many of her poems at a small writing table in her bedroom in Amherst, Massachusetts. Only a handful were published during her lifetime, yet she is now regarded as one of the most significant poets in American literature.',
            'Their habits could hardly be more different, but together they reveal a shared insight: a familiar place, returned to again and again, can make it easier to begin.',
          ],
        },
      },
      vocabulary: [
        { word: 'routine', partOfSpeech: 'noun', definition: 'The usual things you do and the order you do them in', example: 'My morning routine is shower, breakfast, then feeding the cat.', band: 'both' },
        { word: 'distract', partOfSpeech: 'verb', definition: 'To take someone’s attention away from what they are doing', example: 'The music next door distracted me from my maths homework.', band: 'both' },
        { word: 'published', partOfSpeech: 'verb', definition: 'Printed or put online for the public to read', example: 'The school magazine published my review of the new film.', band: 'both' },
        { word: 'approach', partOfSpeech: 'noun', definition: 'A way of dealing with a task or problem', example: 'My approach to revision is to test myself with flashcards.', band: '7-8' },
        { word: 'habit', partOfSpeech: 'noun', definition: 'Something you do regularly, often without thinking about it', example: 'Reading for ten minutes before bed has become a good habit.', band: '7-8' },
        { word: 'essential', partOfSpeech: 'adjective', definition: 'Completely necessary', example: 'Water is essential on a long bike ride.', band: '9-10' },
        { word: 'concentration', partOfSpeech: 'noun', definition: 'The ability to keep all your attention on one thing', example: 'The chess players sat in silence, full of concentration.', band: '9-10' },
        { word: 'significant', partOfSpeech: 'adjective', definition: 'Important enough to be noticed or to have an effect', example: 'Joining the choir made a significant difference to her confidence.', band: '9-10' },
      ],
      quiz: [
        {
          id: 'q1',
          skill: 'main-idea',
          question: 'What is the story mainly about?',
          choices: [
            'Why every writer needs a hut in the garden',
            'How to get a poem published',
            'The places and routines three famous writers chose for their work',
            'The best hotels for writers in America',
          ],
          answerIndex: 2,
          explanation: 'The story describes where Roald Dahl, Maya Angelou and Emily Dickinson wrote, and what their habits had in common.',
        },
        {
          id: 'q2',
          skill: 'detail',
          question: 'What did Maya Angelou ask the hotel to do?',
          choices: ['Take the pictures off the walls', 'Bring her breakfast at dawn', 'Give her a room with a garden view', 'Provide a desk and a new pencil'],
          answerIndex: 0,
          explanation: 'The story says “she asked for the pictures to be taken off the walls, so that nothing would distract her.”',
        },
        {
          id: 'q3',
          skill: 'inference',
          question: 'Why do you think Maya Angelou brought so few things to her hotel room?',
          choices: [
            'The hotel did not allow guests to bring bags',
            'She wanted as few distractions as possible while she wrote',
            'She planned to stay for only a few minutes',
            'She did not own many books',
          ],
          answerIndex: 1,
          explanation: 'She even had the pictures removed “so that nothing would distract her,” so bringing very little fits the same goal.',
        },
        {
          id: 'q4',
          skill: 'vocabulary',
          question: 'The writers each had a very different “routine.” What does “routine” mean in the story?',
          choices: [
            'A short dance performed on stage',
            'A place where writers go on holiday',
            'A tool for writing quickly',
            'The usual things someone does and the order they do them in',
          ],
          answerIndex: 3,
          explanation: 'The story describes what each writer did regularly, like Angelou arriving early each morning, which is their routine.',
        },
        {
          id: 'q5',
          skill: 'sequence',
          question: 'In which order does the story describe the writers?',
          choices: [
            'Emily Dickinson, then Maya Angelou, then Roald Dahl',
            'Maya Angelou, then Roald Dahl, then Emily Dickinson',
            'Roald Dahl, then Emily Dickinson, then Maya Angelou',
            'Roald Dahl, then Maya Angelou, then Emily Dickinson',
          ],
          answerIndex: 3,
          explanation: 'The story starts with Roald Dahl’s hut, moves to Maya Angelou’s hotel room and ends with Emily Dickinson’s bedroom.',
        },
      ],
      writingPrompts: [
        {
          id: 'p1',
          kind: 'summary',
          prompt: 'Summarise what the three writers had in common and how they were different, in three or four sentences.',
          minWords: 40,
          maxWords: 90,
          tips: ['Name each writer and their place.', 'Say what they shared.', 'Keep each sentence focused on one idea.'],
        },
        {
          id: 'p2',
          kind: 'creative',
          prompt: 'Describe your perfect place to write or think. What would be in it, and what would you keep out? Use at least two senses.',
          minWords: 80,
          maxWords: 200,
          tips: ['Start with the first thing you would notice when you walk in.', 'Include sounds, smells or textures, not just what you see.', 'Explain why you would leave some things out.'],
        },
        {
          id: 'p3',
          kind: 'opinion',
          prompt: 'Does where you work really change how well you work? Give your opinion, with one example from the story and one from your own life.',
          minWords: 60,
          maxWords: 150,
          tips: ['Answer the question in your first sentence.', 'Use “for example” to introduce each example.', 'Finish by explaining what you would change about where you work.'],
        },
      ],
      discussion: [
        'Where do you find it easiest to concentrate, and why do you think that is?',
        'Emily Dickinson published very little while she was alive. Why might someone keep writing without an audience?',
      ],
    },
  },
];
