import type { PracticeStory } from '@/lib/literacy/samples';

/** Practice stories: Games (see samples.ts). Evergreen, fact-checked, hand-written at both levels. */
export const GAMES_PRACTICE: readonly PracticeStory[] = [
  {
    slug: 'practice-game-music-that-changes',
    category: 'games',
    title: 'Why video game music changes as you play',
    excerpt:
      'Nobody knows how long a player will spend in a level, so game music has to loop, give warnings and change with the action. This practice story explains how composers write music that reacts to players.',
    publishedAt: '2026-01-08T09:00:00.000Z',
    content: {
      keyIdea: 'Because players decide how long everything takes, game composers write music that loops smoothly, gives information and changes with the action.',
      levels: {
        '7-8': {
          title: 'Why video game music changes as you play',
          paragraphs: [
            'Think of a film soundtrack. It plays the same way every time, because the film always lasts the same length. Games are different. Nobody knows how long a player will spend exploring a level, so game music has to work in a special way.',
            'In early video games, there was very little memory for sound. Composers wrote short tunes that repeated over and over. The trick was to make each loop join smoothly, so that players would not notice where the tune started again.',
            'Composers also used music to give players information. In Super Mario Bros., released in 1985, the music by Koji Kondo suddenly speeds up when the timer is running low. Players quickly learn that the faster tune means they must hurry.',
            'Many modern games use adaptive music, which changes to match what is happening. A calm melody might play while you explore. When danger appears, extra layers such as drums are added. When things calm down, the layers fade out again.',
            'All of this makes game music a tricky challenge. It has to sound good for hours and react to choices that the composer cannot predict.',
          ],
        },
        '9-10': {
          title: 'The music that listens to the player',
          paragraphs: [
            'A film soundtrack can be written to the second, because every viewer sees the same scenes for the same length of time. Game composers have no such certainty. One player might race through a level in two minutes while another lingers for twenty, so the music has to stretch, repeat and respond without ever sounding awkward.',
            'In the earliest home consoles, memory for sound was extremely limited, so composers relied on short melodies that looped continuously. The skill lay in disguising the join: a well-crafted loop ends in a way that leads naturally back to its beginning, allowing a tune to repeat for hours without the seam becoming obvious.',
            'Music could also carry information. In Super Mario Bros., released in 1985, Koji Kondo’s cheerful theme abruptly speeds up when the timer is running low, and players soon learn to treat that change in tempo as a warning to hurry, long before they glance at the clock.',
            'Many modern games take this further with adaptive music, which shifts according to what is happening on screen. A gentle melody might accompany quiet exploration; as danger approaches, additional layers such as percussion are introduced, and when the tension eases they gradually fade away. Because these changes follow the player’s choices, the composer must anticipate many possible paths rather than a single fixed sequence.',
            'The result is music that, in a sense, listens to the player, and the best adaptive scores are so seamless that many players never notice the work involved.',
          ],
        },
      },
      vocabulary: [
        { word: 'adaptive', partOfSpeech: 'adjective', definition: 'Able to change to suit what is happening', example: 'The adaptive lights in the hall get brighter when the room gets darker.', band: 'both' },
        { word: 'notice', partOfSpeech: 'verb', definition: 'To see or become aware of something', example: 'Did you notice that the clock in the hall is ten minutes fast?', band: 'both' },
        { word: 'predict', partOfSpeech: 'verb', definition: 'To say what you think will happen before it happens', example: 'Can you predict who will win the quiz this year?', band: '7-8' },
        { word: 'challenge', partOfSpeech: 'noun', definition: 'Something difficult that tests your skill', example: 'Learning to skateboard down the ramp was a real challenge.', band: '7-8' },
        { word: 'react', partOfSpeech: 'verb', definition: 'To do or change something because of what has just happened', example: 'Goalkeepers have to react in a split second.', band: '7-8' },
        { word: 'obvious', partOfSpeech: 'adjective', definition: 'Easy to see or understand', example: 'It was obvious from his grin that he had passed the test.', band: '9-10' },
        { word: 'anticipate', partOfSpeech: 'verb', definition: 'To expect something and get ready for it', example: 'The café anticipated a busy Saturday and baked extra cakes.', band: '9-10' },
        { word: 'sequence', partOfSpeech: 'noun', definition: 'A set of things that happen in a particular order', example: 'Follow the sequence of steps to build the model.', band: '9-10' },
      ],
      quiz: [
        {
          id: 'q1',
          skill: 'main-idea',
          question: 'What is the main idea of the story?',
          choices: [
            'Early games had better music than modern games',
            'Game music is designed to repeat and change because players control how long things take',
            'Film soundtracks are harder to write than game music',
            'Game music is only there to make players hurry',
          ],
          answerIndex: 1,
          explanation: 'The story explains that “nobody knows how long a player will spend” in a level, so game music loops, gives warnings and adapts.',
        },
        {
          id: 'q2',
          skill: 'detail',
          question: 'What happens to the music in Super Mario Bros. when the timer is running low?',
          choices: ['It stops completely', 'It gets quieter', 'It speeds up', 'It changes to a song about time'],
          answerIndex: 2,
          explanation: 'The story says the music “suddenly speeds up when the timer is running low.”',
        },
        {
          id: 'q3',
          skill: 'inference',
          question: 'Why did early game composers need their loops to join smoothly?',
          choices: [
            'Because players could choose their own music',
            'Because the games came with a film soundtrack',
            'Because loops made the games use more memory',
            'Because the same short tune played again and again, and a clumsy join would be noticed',
          ],
          answerIndex: 3,
          explanation: 'Short tunes “repeated over and over,” so a rough join would stand out every time the tune started again.',
        },
        {
          id: 'q4',
          skill: 'vocabulary',
          question: 'Many modern games use “adaptive” music. What does “adaptive” mean?',
          choices: ['Able to change to suit what is happening', 'Copied from a famous film', 'Played only at the start of a game', 'Very loud and fast'],
          answerIndex: 0,
          explanation: 'The story says adaptive music “changes to match what is happening,” such as adding drums when danger appears.',
        },
        {
          id: 'q5',
          skill: 'sequence',
          question: 'In the story’s example of adaptive music, what happens first?',
          choices: ['Extra layers such as drums are added', 'A calm melody plays while you explore', 'The layers fade out again', 'Danger appears'],
          answerIndex: 1,
          explanation: 'The example begins with “a calm melody” while you explore; danger, extra layers and fading out come after.',
        },
      ],
      writingPrompts: [
        {
          id: 'p1',
          kind: 'summary',
          prompt: 'Summarise, in three or four sentences, why game music works differently from film music.',
          minWords: 40,
          maxWords: 90,
          tips: ['Start with the main difference between games and films.', 'Include one example from the story.', 'Use the word “loop” or “adaptive” correctly.'],
        },
        {
          id: 'p2',
          kind: 'opinion',
          prompt: 'Does music make a game more fun, or could you enjoy it just as much with the sound off? Explain your view with two reasons.',
          minWords: 60,
          maxWords: 150,
          tips: ['Give your answer in the first sentence.', 'Support each reason with an example.', 'Admit one point on the other side.'],
        },
        {
          id: 'p3',
          kind: 'creative',
          prompt: 'Describe a moment in a game you know, or invent one, and explain step by step how the music should change as the moment unfolds.',
          minWords: 80,
          maxWords: 200,
          tips: ['Set the scene before anything happens.', 'Use time words such as “then” and “suddenly”.', 'Describe the sounds precisely: instruments, speed, volume.'],
        },
      ],
      discussion: [
        'Think of a tune from a game, film or show that you remember well. Why do you think it stuck in your mind?',
        'Should music always tell players how to feel, or can silence work better? When?',
      ],
    },
  },
  {
    slug: 'practice-chess-long-journey',
    category: 'games',
    title: 'The long journey of chess',
    excerpt:
      'Chess began in India around 1,500 years ago and changed as it travelled through Persia to Europe. This practice story explains how a rule change about 500 years ago turned the queen into the most powerful piece on the board.',
    publishedAt: '2026-01-09T09:00:00.000Z',
    content: {
      keyIdea: 'Chess changed a great deal as it travelled from India to Europe, and a rule change about 500 years ago created the faster game played today.',
      levels: {
        '7-8': {
          title: 'The long journey of chess',
          paragraphs: [
            'Chess is played by millions of people around the world, in parks, schools and online. But the game did not always look the way it does today. It changed as it travelled from country to country.',
            'Historians believe chess began in India around 1,500 years ago, in a game called chaturanga. From there it spread to Persia, where it was known as shatranj. Traders and travellers carried the game further, and it reached Europe more than a thousand years ago.',
            'The early game was much slower than modern chess. The piece that stood beside the king could move only one square diagonally. Today that piece is the queen, the most powerful piece on the board.',
            'The big change came in Europe about 500 years ago. The rules were adjusted so that the queen could move any distance in a straight line or diagonally. Bishops could travel further, too. Games became faster and more exciting, and players had to invent new strategies.',
            'Chess shows that even a very old game can evolve. The version you play today is the result of centuries of small changes made by players in many different places.',
          ],
        },
        '9-10': {
          title: 'How chess travelled the world and changed along the way',
          paragraphs: [
            'Chess is so familiar today, played in parks, classrooms and millions of online matches, that it is easy to imagine it has always existed in its current form. In fact, the game has been reshaped repeatedly as it passed between cultures over roughly one and a half thousand years.',
            'Historians generally trace its origins to India around the sixth century, to a game called chaturanga, whose pieces included elephants, horses and chariots. From India it spread to Persia, where it became known as shatranj, and then across the Islamic world, carried by merchants and travellers. By more than a thousand years ago, it had reached Europe.',
            'The early game was considerably slower than the one played now. The piece positioned beside the king, which would eventually become the queen, could advance just one square diagonally, and the piece that became the bishop was similarly restricted. Checkmates took patience, and games could stretch on for a very long time.',
            'The decisive transformation occurred in Europe roughly 500 years ago, when new rules allowed the queen to move any distance along straight lines and diagonals, and gave the bishop far greater range. Within a few decades, the queen had become the most powerful piece on the board, games had grown faster and more daring, and players were forced to develop entirely new strategies.',
            'The history of chess is a reminder that even the most traditional games evolve. The version played today is the product of centuries of experiment and adaptation, and every player who learns it inherits those changes.',
          ],
        },
      },
      vocabulary: [
        { word: 'evolve', partOfSpeech: 'verb', definition: 'To change slowly over a long time', example: 'Phones have evolved from bulky boxes into thin screens.', band: 'both' },
        { word: 'strategies', partOfSpeech: 'noun', definition: 'Plans for achieving a goal', example: 'Our team tried two different strategies in the second half.', band: 'both' },
        { word: 'adjusted', partOfSpeech: 'verb', definition: 'Changed slightly so that something works better', example: 'She adjusted her bike seat so her feet could reach the pedals.', band: '7-8' },
        { word: 'invent', partOfSpeech: 'verb', definition: 'To create something new that did not exist before', example: 'We tried to invent a card game using only one deck.', band: '7-8' },
        { word: 'result', partOfSpeech: 'noun', definition: 'Something that happens because of something else', example: 'His neat handwriting is the result of years of practice.', band: '7-8' },
        { word: 'origins', partOfSpeech: 'noun', definition: 'The place or point where something begins', example: 'The museum explains the origins of the town’s famous festival.', band: '9-10' },
        { word: 'transformation', partOfSpeech: 'noun', definition: 'A complete change in what something is like', example: 'The old warehouse went through a transformation and became a climbing centre.', band: '9-10' },
        { word: 'traditional', partOfSpeech: 'adjective', definition: 'Done or made in the way it has been for a long time', example: 'My family eats a traditional meal together on New Year’s Day.', band: '9-10' },
      ],
      quiz: [
        {
          id: 'q1',
          skill: 'main-idea',
          question: 'What is the main idea of the story?',
          choices: [
            'Chess was invented in Europe about 500 years ago',
            'The queen has always been the strongest chess piece',
            'Chess is now mostly played online',
            'Chess changed over many centuries as it spread from India to Europe',
          ],
          answerIndex: 3,
          explanation: 'The story follows chess from India to Persia to Europe and explains how its rules changed along the way.',
        },
        {
          id: 'q2',
          skill: 'detail',
          question: 'Where do historians believe chess began?',
          choices: ['Persia', 'India', 'Europe', 'China'],
          answerIndex: 1,
          explanation: 'The story says “historians believe chess began in India around 1,500 years ago.”',
        },
        {
          id: 'q3',
          skill: 'inference',
          question: 'Why did games become faster after the rule change?',
          choices: [
            'The queen and bishops could cover much more of the board in one move',
            'Players were given less time to think',
            'The board was made smaller',
            'The king was taken out of the game',
          ],
          answerIndex: 0,
          explanation: 'After the change, the queen “could move any distance” and bishops “could travel further,” so the game moved more quickly.',
        },
        {
          id: 'q4',
          skill: 'vocabulary',
          question: '“Chess shows that even a very old game can evolve.” What does “evolve” mean?',
          choices: ['Stay exactly the same', 'Become less popular', 'Change slowly over a long time', 'Be played outdoors'],
          answerIndex: 2,
          explanation: 'The story describes “centuries of small changes,” which is what it means for a game to evolve.',
        },
        {
          id: 'q5',
          skill: 'sequence',
          question: 'Which list shows chess’s journey in the right order?',
          choices: ['Persia, then India, then Europe', 'Europe, then Persia, then India', 'India, then Europe, then Persia', 'India, then Persia, then Europe'],
          answerIndex: 3,
          explanation: 'Chess began in India, “spread to Persia” and later “reached Europe.”',
        },
      ],
      writingPrompts: [
        {
          id: 'p1',
          kind: 'summary',
          prompt: 'Summarise the journey of chess in three or four sentences, from its beginning to the game played today.',
          minWords: 40,
          maxWords: 90,
          tips: ['Keep the events in order.', 'Include the big rule change.', 'Use time words such as “first”, “later” and “today”.'],
        },
        {
          id: 'p2',
          kind: 'headline',
          prompt: 'Write a headline announcing the new, more powerful queen as if the rule change had just happened. Add one sentence explaining your choice of words.',
          minWords: 15,
          maxWords: 50,
          tips: ['Use a strong verb.', 'Keep the headline under 12 words.', 'Make sure it is accurate, not just exciting.'],
        },
        {
          id: 'p3',
          kind: 'opinion',
          prompt: 'If you could change one rule in a game you know, what would it be and why? Give two reasons.',
          minWords: 60,
          maxWords: 150,
          tips: ['Explain the rule as it is now.', 'Describe your change clearly.', 'Say how your change would affect players.'],
        },
      ],
      discussion: [
        'Why do you think chess has stayed popular for so long?',
        'Can you think of another game or sport whose rules have changed? Did the change make it better?',
      ],
    },
  },
  {
    slug: 'practice-game-testers',
    category: 'games',
    title: 'Game testers: finding problems before players do',
    excerpt:
      'Before a game is released, testers play unfinished versions to find bugs, then write clear reports so developers can fix them. This practice story looks at why testing is careful, patient work, and why good writing is part of the job.',
    publishedAt: '2026-01-10T09:00:00.000Z',
    content: {
      keyIdea: 'Game testers hunt for problems in unfinished games and describe them clearly, because a bug that cannot be repeated usually cannot be fixed.',
      levels: {
        '7-8': {
          title: 'Game testers: finding problems before players do',
          paragraphs: [
            'Before a video game is released, it has to be tested. Game testers play unfinished versions of a game to find problems, which are called bugs. Their job is to find the bugs before players do.',
            'Testing is not the same as playing for fun. A tester might walk into the same wall a hundred times, or press buttons at strange moments, to see whether the game breaks. They try the unusual things that a player might one day attempt.',
            'Finding a bug is only half the job. The tester then has to describe it clearly in a bug report. A good report explains the exact steps that make the bug happen, what the tester expected, and what actually happened. Many reports also include a screenshot or a short video.',
            'Clear writing matters, because the developer who fixes the bug may never have seen it. If they cannot follow the steps, they cannot repeat the problem, and it may never get fixed.',
            'Some testers have special tasks. They might check that translated text fits on the screen, or that the game can be played by people with different needs. It is careful, patient work, and it helps make games better for everyone.',
          ],
        },
        '9-10': {
          title: 'Inside the job of breaking games on purpose',
          paragraphs: [
            'Long before a video game reaches players, it passes through the hands of quality assurance testers, whose job is to find its faults. They play unfinished versions of the game, known as builds, searching for bugs: anything from a character stuck inside a wall to a menu that crashes the entire program.',
            'The work differs sharply from playing for enjoyment. A tester may repeat a single action dozens of times, approach a level in deliberately strange ways or press buttons at precisely the wrong moment, because players eventually attempt almost everything. The aim is to expose problems in a controlled setting rather than leave them for the public to discover.',
            'Detecting a bug is only the beginning. The tester must then document it in a bug report, a short technical text that lists the precise steps needed to reproduce the problem, the result they expected and the result they observed, often supported by screenshots or video. The quality of this writing matters enormously: a developer who cannot reproduce a bug is unlikely to be able to fix it.',
            'Testing also includes specialised roles. Localisation testers confirm that translated text fits on screen and makes sense in context, while accessibility testers check that people with different needs can play. It is demanding, methodical work, and much of it remains invisible to the players who benefit from it. When a game launches smoothly, that invisibility is a sign that the testers did their job well.',
          ],
        },
      },
      vocabulary: [
        { word: 'attempt', partOfSpeech: 'verb', definition: 'To try to do something, especially something difficult', example: 'She will attempt to swim the whole length underwater.', band: 'both' },
        { word: 'expected', partOfSpeech: 'verb', definition: 'Thought that something would happen', example: 'We expected rain, but the sun shone all afternoon.', band: 'both' },
        { word: 'describe', partOfSpeech: 'verb', definition: 'To say what something or someone is like', example: 'Describe your dream holiday in three sentences.', band: '7-8' },
        { word: 'repeat', partOfSpeech: 'verb', definition: 'To do or say something again', example: 'Could you repeat the instructions? I missed the last part.', band: 'both' },
        { word: 'patient', partOfSpeech: 'adjective', definition: 'Able to keep going calmly without getting annoyed', example: 'Be patient: the bread needs another ten minutes in the oven.', band: '7-8' },
        { word: 'document', partOfSpeech: 'verb', definition: 'To write down or record information about something', example: 'Our class documented every insect we found in the school garden.', band: '9-10' },
        { word: 'expose', partOfSpeech: 'verb', definition: 'To uncover something so it can be seen', example: 'The low tide exposed rock pools full of crabs.', band: '9-10' },
        { word: 'methodical', partOfSpeech: 'adjective', definition: 'Done carefully, one step at a time, in a planned order', example: 'He is methodical when he packs, ticking each item off a list.', band: '9-10' },
      ],
      quiz: [
        {
          id: 'q1',
          skill: 'main-idea',
          question: 'What is the story mainly about?',
          choices: [
            'Game testers are paid to play finished games for fun',
            'Game testers find problems in unfinished games and explain them clearly so they can be fixed',
            'Most bugs are caused by players pressing buttons too quickly',
            'Games are tested only after they have been sold',
          ],
          answerIndex: 1,
          explanation: 'The story describes how testers look for bugs before release and write reports that help developers fix them.',
        },
        {
          id: 'q2',
          skill: 'detail',
          question: 'According to the story, what does a good bug report include?',
          choices: ['The tester’s score in the game', 'A plan for the next game', 'The exact steps that make the bug happen', 'A review of the game’s story'],
          answerIndex: 2,
          explanation: 'A good report “explains the exact steps that make the bug happen, what the tester expected, and what actually happened.”',
        },
        {
          id: 'q3',
          skill: 'inference',
          question: 'Why might a tester walk into the same wall a hundred times?',
          choices: [
            'Because the tester is stuck and cannot move',
            'To make the game run faster',
            'Because walls are the most important part of a game',
            'To check whether the game breaks in a way a player might one day discover',
          ],
          answerIndex: 3,
          explanation: 'Testers “try the unusual things that a player might one day attempt,” to see whether the game breaks.',
        },
        {
          id: 'q4',
          skill: 'vocabulary',
          question: 'Testing is “patient” work. What does “patient” mean here?',
          choices: [
            'Able to keep going calmly without getting annoyed',
            'A person who is being treated by a doctor',
            'Finished very quickly',
            'Done by a very large team',
          ],
          answerIndex: 0,
          explanation: 'Repeating the same action again and again takes calm, steady effort, which is what “patient” means here.',
        },
        {
          id: 'q5',
          skill: 'purpose',
          question: 'Why does the writer explain what happens when a developer cannot follow the steps in a report?',
          choices: [
            'To blame developers for not fixing bugs',
            'To show why clear writing is an important part of a tester’s job',
            'To explain how to become a developer',
            'To show that bugs usually fix themselves',
          ],
          answerIndex: 1,
          explanation: 'The story says “clear writing matters,” because a problem that cannot be repeated “may never get fixed.”',
        },
      ],
      writingPrompts: [
        {
          id: 'p1',
          kind: 'summary',
          prompt: 'Summarise what a game tester does in three or four sentences, for someone who thinks it just means playing games all day.',
          minWords: 40,
          maxWords: 90,
          tips: ['Start by correcting the common idea.', 'Explain both finding and reporting bugs.', 'End with why the job matters.'],
        },
        {
          id: 'p2',
          kind: 'letter',
          prompt: 'Write a short message to the makers of a game, app or website reporting a problem (real or invented). Include the steps to make it happen, what you expected and what actually happened.',
          minWords: 60,
          maxWords: 150,
          tips: ['Number the steps in order.', 'Be exact: say which button, which screen, which level.', 'Stay polite and calm.'],
        },
        {
          id: 'p3',
          kind: 'opinion',
          prompt: 'Would you enjoy working as a game tester? Explain your answer with two reasons from the story.',
          minWords: 60,
          maxWords: 150,
          tips: ['Give your answer in the first sentence.', 'Use details from the story as evidence.', 'Mention one part of the job you might find hard.'],
        },
      ],
      discussion: [
        'Why is it hard to explain a problem to someone who has not seen it happen?',
        'Apart from games, where else might careful testing matter?',
      ],
    },
  },
];
