import type { PracticeStory } from '@/lib/literacy/samples';

/** Practice stories: Sports (see samples.ts). Evergreen, fact-checked, hand-written at both levels. */
export const SPORTS_PRACTICE: readonly PracticeStory[] = [
  {
    slug: 'practice-marathon-distance',
    category: 'sports',
    title: 'Why a marathon is 42.195 kilometres',
    excerpt:
      'The marathon is named after a town in Greece, but its exact length comes from the route of the 1908 London Olympics. This practice story explains how an odd distance became the official one.',
    publishedAt: '2026-01-14T09:00:00.000Z',
    content: {
      keyIdea: 'The marathon is named after a Greek legend, but its exact distance of 42.195 kilometres comes from the course of the 1908 London Olympics.',
      levels: {
        '7-8': {
          title: 'Why a marathon is 42.195 kilometres',
          paragraphs: [
            'A marathon is exactly 42.195 kilometres, or about 26.2 miles. Most races have round numbers, like 5 or 10 kilometres. A marathon’s length is a strange, precise number. So where does it come from?',
            'The race is named after Marathon, a town in Greece. According to an ancient legend, a messenger ran from Marathon to Athens to announce that the Greeks had won an important battle. Historians are not sure the run really happened, but the story inspired a new race.',
            'When the first modern Olympic Games were held in Athens in 1896, they included a long race from Marathon to the city, about 40 kilometres. It was won by a Greek runner named Spyridon Louis. For the next few years, marathons had no fixed length.',
            'That changed at the 1908 Olympics in London. The course started at Windsor Castle and finished in front of the royal box in the Olympic stadium. It measured 26 miles and 385 yards, which is 42.195 kilometres.',
            'In 1921, the organisation that runs international athletics made that distance official. So every marathon runner today covers a distance first chosen for one race in London more than a hundred years ago.',
          ],
        },
        '9-10': {
          title: 'The surprising history behind the marathon’s odd distance',
          paragraphs: [
            'Few sporting distances are as oddly precise as the marathon’s 42.195 kilometres. Runners train for months to cover it, yet many have no idea why the race is that length rather than a tidy 40 or 42 kilometres.',
            'The event takes its name from Marathon, a town in Greece. An ancient legend, written down centuries after the events it describes, tells of a messenger who ran from Marathon to Athens to announce a Greek victory in battle. Historians doubt that the run took place as the legend claims, but the tale captured the imagination of the people who organised the first modern Olympics.',
            'At those Games, held in Athens in 1896, a race of roughly 40 kilometres was staged along the route from Marathon to the city, and the Greek runner Spyridon Louis won it, to the delight of the home crowd. In the years that followed, however, marathon courses varied considerably in length, depending on the route each organiser chose.',
            'The decisive moment came at the 1908 Olympics in London. Organisers planned a course that began at Windsor Castle and ended in front of the royal box inside the Olympic stadium, a route measuring 26 miles and 385 yards, or 42.195 kilometres. Finishing in front of the royal box, rather than at a round number, is what added those awkward final yards.',
            'That figure might have remained a one-off. In 1921, however, the international organisation for athletics adopted it as the official standard, which means every marathon since has preserved, down to the metre, a distance shaped by one race in London.',
          ],
        },
      },
      vocabulary: [
        { word: 'precise', partOfSpeech: 'adjective', definition: 'Exact and accurate', example: 'The recipe needs precise measurements, so use the scales.', band: 'both' },
        { word: 'legend', partOfSpeech: 'noun', definition: 'An old, famous story that may not be completely true', example: 'A local legend says a giant built the rocky path across the bay.', band: 'both' },
        { word: 'announce', partOfSpeech: 'verb', definition: 'To tell people something officially or publicly', example: 'The head teacher will announce the winners in assembly.', band: 'both' },
        { word: 'official', partOfSpeech: 'adjective', definition: 'Approved by the people in charge', example: 'The official start time of the race is nine o’clock.', band: 'both' },
        { word: 'inspired', partOfSpeech: 'verb', definition: 'Gave someone the idea or the wish to do something', example: 'Watching the gymnastics final inspired me to join a club.', band: '7-8' },
        { word: 'considerably', partOfSpeech: 'adverb', definition: 'By a large amount', example: 'The new bus route is considerably faster than the old one.', band: '9-10' },
        { word: 'standard', partOfSpeech: 'noun', definition: 'An agreed rule or measure that everyone uses', example: 'Football pitches must meet a standard size for official matches.', band: '9-10' },
        { word: 'preserved', partOfSpeech: 'verb', definition: 'Kept safe and unchanged', example: 'The old mill has been preserved exactly as it was.', band: '9-10' },
      ],
      quiz: [
        {
          id: 'q1',
          skill: 'main-idea',
          question: 'What is the main idea of the story?',
          choices: [
            'Marathons have been exactly 42.195 kilometres since ancient times',
            'The first marathon was run in London',
            'The marathon’s exact distance comes from the route of the 1908 London Olympics',
            'Marathon runners choose their own distance',
          ],
          answerIndex: 2,
          explanation: 'The story explains that the 1908 London course measured 42.195 kilometres, and that this length was made official in 1921.',
        },
        {
          id: 'q2',
          skill: 'detail',
          question: 'Who won the marathon at the 1896 Olympics?',
          choices: ['A messenger from Athens', 'A runner from London', 'Nobody, because the race was cancelled', 'Spyridon Louis, a Greek runner'],
          answerIndex: 3,
          explanation: 'The story says the race “was won by a Greek runner named Spyridon Louis.”',
        },
        {
          id: 'q3',
          skill: 'inference',
          question: 'Why does the story say that historians “are not sure the run really happened”?',
          choices: [
            'To show that the messenger story is a legend rather than a proven fact',
            'Because the town of Marathon does not exist',
            'Because historians think the messenger rode a horse',
            'Because the 1896 race was never written about',
          ],
          answerIndex: 0,
          explanation: 'The run comes from “an ancient legend,” and the writer is careful to separate the legend from known history.',
        },
        {
          id: 'q4',
          skill: 'vocabulary',
          question: 'In 1921, the distance was made “official.” What does “official” mean here?',
          choices: ['Very long and tiring', 'Approved by the people in charge', 'Chosen by the runners', 'Kept secret'],
          answerIndex: 1,
          explanation: 'The organisation that runs international athletics decided on it, so it became the approved distance.',
        },
        {
          id: 'q5',
          skill: 'sequence',
          question: 'Which of these happened first?',
          choices: [
            'The marathon at the 1908 Olympics in London',
            'The distance becoming official in 1921',
            'The marathon at the 1896 Olympics in Athens',
            'Marathons around the world using 42.195 kilometres',
          ],
          answerIndex: 2,
          explanation: 'The Athens race in 1896 came before the London Olympics in 1908 and the official decision in 1921.',
        },
      ],
      writingPrompts: [
        {
          id: 'p1',
          kind: 'summary',
          prompt: 'Summarise, in three or four sentences, how the marathon got its name and its exact distance.',
          minWords: 40,
          maxWords: 90,
          tips: ['Start with the name, then the distance.', 'Include the years 1908 and 1921.', 'Use your own words.'],
        },
        {
          id: 'p2',
          kind: 'opinion',
          prompt: 'Should the marathon be changed to a round 40 kilometres, or should it keep its historic distance? Explain your view.',
          minWords: 60,
          maxWords: 150,
          tips: ['Give your view in the first sentence.', 'Use one fact from the story as evidence.', 'Respond to one argument on the other side.'],
        },
        {
          id: 'p3',
          kind: 'letter',
          prompt: 'Write a short message of encouragement to a friend who is about to run their first long race. Include one fact from the story.',
          minWords: 60,
          maxWords: 150,
          tips: ['Start with a friendly greeting.', 'Use the fact to make your friend smile or feel proud.', 'End with a good wish.'],
        },
      ],
      discussion: [
        'Why do you think people choose to run marathons, even though they are so hard?',
        'Can you think of another rule or tradition that exists because of something that happened only once?',
      ],
    },
  },
  {
    slug: 'practice-sleep-is-training',
    category: 'sports',
    title: 'Why sleep is part of training',
    excerpt:
      'Coaches and scientists say that sleep helps athletes repair their muscles and remember new skills. This practice story looks at the research and what it means for anyone learning something new.',
    publishedAt: '2026-01-15T09:00:00.000Z',
    content: {
      keyIdea: 'Sleep helps the body repair itself and the brain store new skills, so rest is part of how athletes, and everyone else, improve.',
      levels: {
        '7-8': {
          title: 'Why sleep is part of training',
          paragraphs: [
            'When people think about how athletes improve, they usually picture hard training sessions. But many coaches and scientists say there is another important part of getting better, and it happens in bed.',
            'Sleep experts recommend that teenagers get about eight to ten hours of sleep each night. During deep sleep, the body releases a hormone that helps repair muscles after exercise. Sleep also helps the brain remember new skills, so the moves you practise during the day can become more automatic overnight.',
            'Researchers at Stanford University tested this with a college basketball team. For several weeks, the players spent extra time in bed each night. By the end, they ran faster sprints and scored more of their free throws.',
            'Because of research like this, some professional teams now pay close attention to how their athletes sleep. Players are encouraged to keep a regular routine, go to bed at similar times and avoid bright screens late at night.',
            'The lesson is not only for top athletes. Whether you play a sport, learn an instrument or revise for a test, a good night’s sleep helps your brain and body make the most of your effort.',
          ],
        },
        '9-10': {
          title: 'Sleep: the training secret that happens in the dark',
          paragraphs: [
            'Ask how elite athletes improve and most people describe punishing training sessions, carefully planned meals and hours of practice. Increasingly, however, coaches and sports scientists point to something that happens far from the training ground: sleep.',
            'Sleep experts recommend that teenagers get roughly eight to ten hours a night, and there are good biological reasons for that advice. During deep sleep, the body releases growth hormone, which supports the repair of muscles strained by exercise. Sleep also allows the brain to consolidate what it has learned, so that movements rehearsed during the day become more fluent and automatic.',
            'One well-known study, carried out at Stanford University, asked members of a college basketball team to extend their time in bed for several weeks. By the end of the experiment, the players were sprinting faster and scoring a higher proportion of their free throws, improvements achieved without any extra training. The study was small, but its results caught the attention of coaches in many sports.',
            'Findings like these have persuaded some professional teams to track their players’ sleep and to encourage consistent routines: regular bedtimes, cool and dark rooms, and fewer bright screens late at night. Some clubs even employ specialists who advise athletes on how to rest, especially when they travel across time zones.',
            'The implications reach well beyond elite sport. Anyone trying to master a skill, whether a musical instrument, a new language or material for an exam, may find that rest is not a break from progress but an essential part of it.',
          ],
        },
      },
      vocabulary: [
        { word: 'improve', partOfSpeech: 'verb', definition: 'To get better, or to make something better', example: 'My handwriting started to improve once I slowed down.', band: 'both' },
        { word: 'recommend', partOfSpeech: 'verb', definition: 'To suggest that something is a good idea', example: 'The librarian recommended a mystery series I ended up loving.', band: 'both' },
        { word: 'repair', partOfSpeech: 'verb', definition: 'To fix or mend something that is damaged', example: 'My aunt showed me how to repair the zip on my coat.', band: 'both' },
        { word: 'routine', partOfSpeech: 'noun', definition: 'The usual things you do and the order you do them in', example: 'Packing my bag the night before is part of my school routine.', band: '7-8' },
        { word: 'effort', partOfSpeech: 'noun', definition: 'The hard work you put into doing something', example: 'Her poster won a prize because of the effort she put into it.', band: '7-8' },
        { word: 'consolidate', partOfSpeech: 'verb', definition: 'To make something stronger or more secure, such as a memory or a skill', example: 'A short quiz at the end of the lesson helps consolidate what we learned.', band: '9-10' },
        { word: 'consistent', partOfSpeech: 'adjective', definition: 'Staying the same each time', example: 'A consistent bedtime makes it easier to wake up for school.', band: '9-10' },
        { word: 'proportion', partOfSpeech: 'noun', definition: 'A part of a total, compared with the whole amount', example: 'A large proportion of our class walks to school.', band: '9-10' },
      ],
      quiz: [
        {
          id: 'q1',
          skill: 'main-idea',
          question: 'What is the main idea of the story?',
          choices: [
            'Athletes should train at night instead of during the day',
            'Basketball is the best sport for teenagers',
            'Screens are the main reason athletes lose games',
            'Sleep helps the body and brain get the most out of training',
          ],
          answerIndex: 3,
          explanation: 'The story explains how sleep repairs muscles and helps the brain remember skills, so it is “another important part of getting better.”',
        },
        {
          id: 'q2',
          skill: 'detail',
          question: 'How much sleep do experts recommend for teenagers?',
          choices: ['About five to six hours a night', 'About eight to ten hours a night', 'About twelve to fourteen hours a night', 'As much as they like, but only at weekends'],
          answerIndex: 1,
          explanation: 'The story says experts “recommend that teenagers get about eight to ten hours of sleep each night.”',
        },
        {
          id: 'q3',
          skill: 'inference',
          question: 'The Stanford players improved after spending extra time in bed. What does this suggest?',
          choices: [
            'The extra sleep probably helped them play better',
            'Basketball practice does not help players',
            'The players were already the best in the world',
            'Sprints and free throws are easy skills',
          ],
          answerIndex: 0,
          explanation: 'The only change described was more time in bed, so the story suggests that the extra sleep led to the improvement.',
        },
        {
          id: 'q4',
          skill: 'vocabulary',
          question: 'During deep sleep, a hormone helps “repair” muscles. What does “repair” mean here?',
          choices: ['Build something brand new', 'Make something heavier', 'Fix or mend something that is damaged', 'Measure how strong something is'],
          answerIndex: 2,
          explanation: 'Muscles are worked hard “after exercise,” and sleep helps fix them, which is what repair means.',
        },
        {
          id: 'q5',
          skill: 'purpose',
          question: 'Why does the writer end by mentioning instruments and revising for a test?',
          choices: [
            'To suggest that athletes should also learn instruments',
            'To show that the benefits of sleep apply to anyone learning a skill',
            'To explain how to revise for a test',
            'To show that sleep only matters before exams',
          ],
          answerIndex: 1,
          explanation: 'The last paragraph says “the lesson is not only for top athletes,” widening the idea to everyone.',
        },
      ],
      writingPrompts: [
        {
          id: 'p1',
          kind: 'summary',
          prompt: 'Summarise, in three or four sentences, why sleep matters for athletes.',
          minWords: 40,
          maxWords: 90,
          tips: ['Mention what sleep does for the body and the brain.', 'Include the Stanford study.', 'Keep it short and clear.'],
        },
        {
          id: 'p2',
          kind: 'opinion',
          prompt: 'Should schools start later so that teenagers can get more sleep? Give your opinion and two reasons.',
          minWords: 60,
          maxWords: 150,
          tips: ['State your opinion in the first sentence.', 'Use “because” to explain each reason.', 'Think about any problems a later start might cause.'],
        },
        {
          id: 'p3',
          kind: 'letter',
          prompt: 'Write a short note to a younger student explaining why sleep matters for anything they want to get better at. Use one fact from the story.',
          minWords: 60,
          maxWords: 150,
          tips: ['Use friendly, simple language.', 'Include one fact from the story.', 'Give one practical tip for sleeping well.'],
        },
      ],
      discussion: [
        'What makes it hard for people your age to get enough sleep, and what could help?',
        'Why do you think rest is sometimes seen as lazy, even though it helps people improve?',
      ],
    },
  },
  {
    slug: 'practice-hawk-eye',
    category: 'sports',
    title: 'How cameras help referees make the call',
    excerpt:
      'Was the ball in or out? Hawk-Eye uses several high-speed cameras and a computer to track the ball in tennis and cricket. This practice story explains how the system works and why it is accurate but not perfect.',
    publishedAt: '2026-01-16T09:00:00.000Z',
    content: {
      keyIdea: 'Hawk-Eye combines views from several high-speed cameras to judge close calls in sport, which makes decisions fairer, though never completely perfect.',
      levels: {
        '7-8': {
          title: 'How cameras help referees make the call',
          paragraphs: [
            'Was the ball in or out? In tennis and cricket, some of the most important moments come down to a few millimetres. Today, many of those decisions are made with help from a camera system called Hawk-Eye.',
            'Hawk-Eye uses several high-speed cameras placed around the court or ground. Each camera sees the ball from a different angle. A computer combines their views to work out exactly where the ball is and to track its path through the air.',
            'The system was developed in the United Kingdom by Paul Hawkins, a computer scientist. It was first used on television in cricket in 2001, to show viewers where the ball was heading. Later, tennis began using it to check line calls, and players can now challenge a decision they disagree with.',
            'Some major tennis tournaments now use electronic line calling instead of human line judges. In football, goal-line technology tells the referee within about a second whether the whole ball has crossed the line.',
            'The technology is very accurate, but it is not perfect. It has a tiny margin of error, and it predicts part of the ball’s path. Still, many players and fans feel it has made close calls fairer.',
          ],
        },
        '9-10': {
          title: 'Hawk-Eye and the science of the close call',
          paragraphs: [
            'In top-level tennis and cricket, matches can turn on distances smaller than a fingernail. A ball that clips the edge of a line is in; one that misses it by a sliver is out, and the human eye, faced with a ball travelling at enormous speed, cannot always tell the difference.',
            'Hawk-Eye was designed to settle such moments. The system positions several high-speed cameras around a court or ground, each capturing the ball from a different angle. Software combines these views to calculate the ball’s position in three dimensions, reconstruct its flight and, where necessary, predict where it would have travelled.',
            'It was developed in the United Kingdom by the computer scientist Paul Hawkins and first appeared on television during cricket coverage in 2001, initially as a way of showing viewers where the ball was heading. Tennis later adopted it for line calls, allowing players to challenge decisions they believed were wrong, and some major tournaments have since replaced human line judges with electronic line calling altogether.',
            'Football relies on a related idea: goal-line technology alerts the referee, within about a second, when the whole ball has crossed the line, usually through a signal sent to a special watch.',
            'The technology is impressively accurate but not flawless. It works with a small margin of error and relies partly on prediction. Its supporters argue that a consistent, transparent system is fairer than a split-second human judgement; critics reply that it can remove some of the drama and character from sport.',
          ],
        },
      },
      vocabulary: [
        { word: 'accurate', partOfSpeech: 'adjective', definition: 'Correct and exact, without mistakes', example: 'Check that your map is accurate before the orienteering race.', band: 'both' },
        { word: 'combines', partOfSpeech: 'verb', definition: 'Joins or mixes two or more things together', example: 'My favourite recipe combines sweet and sour flavours.', band: 'both' },
        { word: 'developed', partOfSpeech: 'verb', definition: 'Created or invented something new over time', example: 'Our class developed an app to help people find the library.', band: 'both' },
        { word: 'challenge', partOfSpeech: 'verb', definition: 'To question whether something is right or fair', example: 'He challenged the score because he was sure the ball hit the target.', band: 'both' },
        { word: 'margin', partOfSpeech: 'noun', definition: 'An amount by which something could be wrong or different', example: 'The weather forecast allows a small margin for surprise showers.', band: 'both' },
        { word: 'consistent', partOfSpeech: 'adjective', definition: 'Working the same way every time', example: 'A good referee is consistent, giving the same decision for the same foul.', band: '9-10' },
        { word: 'transparent', partOfSpeech: 'adjective', definition: 'Open and easy for people to see and understand', example: 'The club was transparent about how it chose the new captain.', band: '9-10' },
      ],
      quiz: [
        {
          id: 'q1',
          skill: 'main-idea',
          question: 'What is the main idea of the story?',
          choices: [
            'Referees are no longer needed in any sport',
            'Hawk-Eye uses cameras and a computer to help decide close calls in sport',
            'Paul Hawkins invented tennis in 2001',
            'Cricket was the first sport ever shown on television',
          ],
          answerIndex: 1,
          explanation: 'The story explains how Hawk-Eye works, where it is used and how accurate it is.',
        },
        {
          id: 'q2',
          skill: 'detail',
          question: 'How does Hawk-Eye work out where the ball is?',
          choices: [
            'A chip inside the ball sends a signal',
            'A line judge presses a button',
            'One camera films the ball from above',
            'A computer combines views from several high-speed cameras',
          ],
          answerIndex: 3,
          explanation: 'The story says “a computer combines their views to work out exactly where the ball is.”',
        },
        {
          id: 'q3',
          skill: 'inference',
          question: 'Why might a tennis player challenge a line call?',
          choices: [
            'They believe the call was a mistake',
            'They want a rest between points',
            'They want to appear on television',
            'The rules say every point must be checked',
          ],
          answerIndex: 0,
          explanation: 'Players “can now challenge a decision they disagree with,” so they challenge when they think the call was wrong.',
        },
        {
          id: 'q4',
          skill: 'vocabulary',
          question: '“It has a tiny margin of error.” What does “margin of error” mean?',
          choices: [
            'The edge of a tennis court',
            'A mistake made by a player',
            'A small amount by which a measurement could be wrong',
            'The time a referee has to decide',
          ],
          answerIndex: 2,
          explanation: 'The sentence explains why the system is “not perfect”: its measurements can be very slightly off.',
        },
        {
          id: 'q5',
          skill: 'purpose',
          question: 'Why does the writer say the technology “is not perfect”?',
          choices: [
            'To argue that sports should stop using cameras',
            'To explain how to build a camera system',
            'To show that human judges never make mistakes',
            'To give a balanced view by showing its limits as well as its strengths',
          ],
          answerIndex: 3,
          explanation: 'After explaining how accurate Hawk-Eye is, the writer adds its limits, so readers get a fair, balanced picture.',
        },
      ],
      writingPrompts: [
        {
          id: 'p1',
          kind: 'summary',
          prompt: 'Summarise how Hawk-Eye works and where it is used, in three or four sentences.',
          minWords: 40,
          maxWords: 90,
          tips: ['Explain the cameras and the computer.', 'Name at least two sports.', 'Mention one limit of the system.'],
        },
        {
          id: 'p2',
          kind: 'opinion',
          prompt: 'Does technology like Hawk-Eye make sport better, or does it take away some of the fun? Give your opinion and two reasons.',
          minWords: 60,
          maxWords: 150,
          tips: ['State your opinion at the start.', 'Give each reason its own sentence.', 'Include one detail from the story.'],
        },
        {
          id: 'p3',
          kind: 'headline',
          prompt: 'Write two headlines about a match decided by a Hawk-Eye challenge: one from the winner’s point of view and one from the other player’s. Add a sentence explaining the difference.',
          minWords: 20,
          maxWords: 60,
          tips: ['Keep each headline under 12 words.', 'Choose verbs that show each point of view.', 'Make sure both headlines describe the same event.'],
        },
      ],
      discussion: [
        'Would you trust a computer or a person more to make a close call? Why?',
        'What other everyday decisions could technology help people make more fairly?',
      ],
    },
  },
];
