import type { PracticeStory } from '@/lib/literacy/samples';

/** Practice stories: Art (see samples.ts). Evergreen, fact-checked, hand-written at both levels. */
export const ART_PRACTICE: readonly PracticeStory[] = [
  {
    slug: 'practice-great-wave',
    category: 'art',
    title: 'The Great Wave: one picture, thousands of prints',
    excerpt:
      'Hokusai’s Great Wave, made around 1831, is one of the best-known images in the world. This practice story explains how a team of artists, carvers and printers turned one design into thousands of woodblock prints.',
    publishedAt: '2026-01-11T09:00:00.000Z',
    content: {
      keyIdea: 'The Great Wave became famous around the world partly because it is a woodblock print, so thousands of copies could be made from one design.',
      levels: {
        '7-8': {
          title: 'The Great Wave: one picture, thousands of prints',
          paragraphs: [
            'You may have seen it on posters, mugs or phone cases: a huge blue wave with claw-like foam, curling over three small boats. Behind it, far in the distance, sits Mount Fuji.',
            'The picture is usually called The Great Wave. It was made around 1831 by the Japanese artist Katsushika Hokusai, who was about 70 years old at the time. It belongs to a series called Thirty-Six Views of Mount Fuji.',
            'The Great Wave is not a painting. It is a woodblock print. Hokusai drew the design, and skilled carvers cut it into blocks of wood, with a separate block for each colour. Printers then brushed ink onto the blocks and pressed paper against them, one colour at a time.',
            'Because the blocks could be used again and again, thousands of copies were printed and sold. Over time the wood wore down, so the earliest prints have the sharpest lines. Museums around the world now own copies. Many keep them in the dark most of the time, because strong light can make the colours fade.',
            'Hokusai also used a blue pigment called Prussian blue, which had recently become available in Japan. Its deep, lasting colour helped make the wave unforgettable.',
          ],
        },
        '9-10': {
          title: 'How The Great Wave became one of the world’s best-known images',
          paragraphs: [
            'Even people who know nothing about Japanese art tend to recognise it: a towering wave with claw-like fingers of foam, poised to crash over three narrow boats while Mount Fuji sits small and calm in the distance. Few images have travelled so far from their origins, or appeared on so many posters, mugs and phone cases.',
            'Its full title is Under the Wave off Kanagawa, though it is usually called The Great Wave. Katsushika Hokusai created it around 1831, when he was about 70, as part of a series titled Thirty-Six Views of Mount Fuji. Placing the famous mountain in the background, dwarfed by the water, was a bold choice that invites viewers to think about scale and perspective.',
            'Crucially, The Great Wave is a woodblock print rather than a single painting. Producing it involved a team: Hokusai supplied the design, specialist carvers cut it into wooden blocks, one for each colour, and printers applied ink and pressed paper onto each block in turn. The method allowed thousands of impressions to be made, and because the blocks gradually wore down, the earliest impressions are prized for their crisp detail.',
            'Hokusai also took advantage of Prussian blue, a synthetic pigment that had recently become widely available in Japan. Its intense, durable colour gave the sea remarkable depth. Today, museums across the world hold copies, a reminder that an image designed to be reproduced can become more familiar than almost any unique masterpiece. Its influence can be seen in countless later artworks, advertisements and designs.',
          ],
        },
      },
      vocabulary: [
        { word: 'series', partOfSpeech: 'noun', definition: 'A set of similar things that come one after another', example: 'I have read every book in the series, and the last one is my favourite.', band: 'both' },
        { word: 'design', partOfSpeech: 'noun', definition: 'A drawing or plan that shows how something will look', example: 'Her design for the class T-shirt was chosen by a vote.', band: 'both' },
        { word: 'available', partOfSpeech: 'adjective', definition: 'Ready to be used, bought or found', example: 'Tickets for the school play are available at the office.', band: 'both' },
        { word: 'separate', partOfSpeech: 'adjective', definition: 'Different and not joined to anything else', example: 'Keep your trainers in a separate bag from your clean clothes.', band: '7-8' },
        { word: 'skilled', partOfSpeech: 'adjective', definition: 'Having the training and ability to do something well', example: 'A skilled baker can decorate a cake in minutes.', band: '7-8' },
        { word: 'perspective', partOfSpeech: 'noun', definition: 'A way of showing distance and size in a picture, or a way of seeing things', example: 'In the photo, perspective makes the far-off trees look tiny.', band: '9-10' },
        { word: 'durable', partOfSpeech: 'adjective', definition: 'Able to last a long time without breaking or fading', example: 'These durable boots have lasted three muddy winters.', band: '9-10' },
        { word: 'reproduced', partOfSpeech: 'verb', definition: 'Copied so that more versions can be made', example: 'The poster was reproduced so every classroom could have one.', band: '9-10' },
      ],
      quiz: [
        {
          id: 'q1',
          skill: 'main-idea',
          question: 'What is the main idea of the story?',
          choices: [
            'Hokusai painted one huge picture of a storm at sea',
            'A famous Japanese woodblock print was made in thousands of copies and became known worldwide',
            'Mount Fuji is the tallest mountain in the world',
            'Prussian blue was invented by Hokusai',
          ],
          answerIndex: 1,
          explanation: 'The story explains that The Great Wave is a woodblock print, that “thousands of copies were printed” and that museums around the world own them.',
        },
        {
          id: 'q2',
          skill: 'detail',
          question: 'Why do the earliest prints have the sharpest lines?',
          choices: [
            'Hokusai coloured the first copies himself',
            'Later copies were printed on cheaper paper',
            'The ink faded in sunlight over time',
            'The wooden blocks wore down as more copies were printed',
          ],
          answerIndex: 3,
          explanation: 'The story says “over time the wood wore down, so the earliest prints have the sharpest lines.”',
        },
        {
          id: 'q3',
          skill: 'inference',
          question: 'Why could The Great Wave be sold to many people at once?',
          choices: [
            'The same blocks could print many copies of the same picture',
            'Hokusai worked very fast with a brush',
            'It was printed by machines in a factory',
            'Each buyer painted their own copy',
          ],
          answerIndex: 0,
          explanation: 'The blocks “could be used again and again,” so one design could become thousands of prints.',
        },
        {
          id: 'q4',
          skill: 'vocabulary',
          question: 'The picture belongs to a “series.” What is a series?',
          choices: ['A single very large painting', 'A type of wooden block', 'A set of similar things that come one after another', 'A famous mountain in Japan'],
          answerIndex: 2,
          explanation: 'The Great Wave is one of the Thirty-Six Views of Mount Fuji, a set of related pictures.',
        },
        {
          id: 'q5',
          skill: 'sequence',
          question: 'Which step came first in making the print?',
          choices: ['Carvers cut the design into wood', 'Printers brushed ink onto the blocks', 'Paper was pressed against the blocks', 'Hokusai drew the design'],
          answerIndex: 3,
          explanation: '“Hokusai drew the design,” and only then did carvers cut it and printers use the blocks.',
        },
      ],
      writingPrompts: [
        {
          id: 'p1',
          kind: 'summary',
          prompt: 'Summarise how The Great Wave was made, in three or four sentences, for someone who thinks it is a painting.',
          minWords: 40,
          maxWords: 90,
          tips: ['Start by correcting the mistake.', 'Explain the steps in order.', 'Say why so many copies exist.'],
        },
        {
          id: 'p2',
          kind: 'creative',
          prompt: 'Imagine you are in one of the three boats beneath the wave. Describe the moment in the first person, using at least two senses.',
          minWords: 80,
          maxWords: 200,
          tips: ['Start with what you notice first.', 'Include sound, touch or smell as well as sight.', 'End with Mount Fuji in the distance.'],
        },
        {
          id: 'p3',
          kind: 'opinion',
          prompt: 'Is a print that exists in thousands of copies less special than a one-of-a-kind painting? Explain your view.',
          minWords: 60,
          maxWords: 150,
          tips: ['State your view clearly at the start.', 'Use a detail from the story as evidence.', 'Consider what makes a piece of art “special”.'],
        },
      ],
      discussion: [
        'Why do you think this image is still so popular almost 200 years after it was made?',
        'Which picture or photo would you choose to represent the place where you live, and why?',
      ],
    },
  },
  {
    slug: 'practice-museum-storage',
    category: 'art',
    title: 'Why most museum treasures are kept out of sight',
    excerpt:
      'Large museums usually show only a small part of their collections. This practice story explains why fragile objects are rested in careful storage, and how a building in Rotterdam lets visitors look inside.',
    publishedAt: '2026-01-12T09:00:00.000Z',
    content: {
      keyIdea: 'Museums keep most of their objects in carefully controlled storage to save space and protect fragile works, and some are finding ways to let visitors see it.',
      levels: {
        '7-8': {
          title: 'Why most museum treasures are kept out of sight',
          paragraphs: [
            'When you visit a big museum, it can feel as if everything is on display. In fact, most large museums show only a small part of their collection. The rest is kept in storage, often in rooms the public never sees.',
            'There are good reasons for this. Many museums own far more objects than they have space to show. Some items are also fragile. Drawings, photographs and old fabrics can fade if they are exposed to light for too long, so they are shown for a few months and then rested in the dark.',
            'Storage rooms are carefully controlled. The temperature and the amount of moisture in the air stay steady, because sudden changes can crack wood or damage paint. Experts called conservators check the objects and repair them when needed. Researchers visit to study them, too.',
            'Some museums are finding ways to share their hidden collections. In Rotterdam, in the Netherlands, a storage building called Depot Boijmans Van Beuningen opened in 2021. Visitors can walk through it and see thousands of artworks being stored and cared for. The building itself is shaped like a giant bowl and covered in mirrors.',
          ],
        },
        '9-10': {
          title: 'The hidden collections behind every museum',
          paragraphs: [
            'Stroll through the galleries of a major museum and it is easy to believe you are seeing its whole collection. In reality, the opposite is usually true: large museums typically display only a small fraction of what they own, while the vast majority of objects are kept in storage, out of public view and sometimes in separate buildings miles from the galleries.',
            'Space is one explanation, since collections tend to grow far faster than galleries can expand. Preservation is another. Works on paper, photographs and historic textiles deteriorate when exposed to light, so many are displayed for only a few months before being returned to darkness to rest. Keeping them hidden is, in a sense, a way of protecting them for future generations.',
            'Stores are far from forgotten cupboards. Temperature and humidity are tightly regulated, because rapid changes can split wood, warp canvas or loosen paint. Conservators monitor the condition of objects and carry out repairs, while researchers regularly ask to study items that may never go on display. Objects are catalogued with numbered records, so staff can find each one among thousands of others, and some travel from storage to exhibitions at other museums around the world.',
            'Increasingly, museums are experimenting with ways to make these hidden collections visible. In Rotterdam, the Depot Boijmans Van Beuningen, which opened in 2021, is a storage building designed to be visited. Its bowl-shaped exterior is covered in mirrored panels, and inside, the public can watch as thousands of artworks are stored, studied and cared for, challenging the idea that storage has to mean secrecy.',
          ],
        },
      },
      vocabulary: [
        { word: 'display', partOfSpeech: 'noun', definition: 'A show of things arranged for people to look at', example: 'The library has a display of books about space near the door.', band: 'both' },
        { word: 'exposed', partOfSpeech: 'verb', definition: 'Left without protection from something, such as light or weather', example: 'Plants exposed to frost overnight can turn brown.', band: 'both' },
        { word: 'fragile', partOfSpeech: 'adjective', definition: 'Easily broken or damaged', example: 'Wrap the fragile glass bowl in newspaper before you pack it.', band: '7-8' },
        { word: 'repair', partOfSpeech: 'verb', definition: 'To fix something that is broken or damaged', example: 'My uncle showed me how to repair a flat bike tyre.', band: '7-8' },
        { word: 'steady', partOfSpeech: 'adjective', definition: 'Staying the same, without sudden changes', example: 'Keep a steady pace so you do not get tired too quickly.', band: '7-8' },
        { word: 'fraction', partOfSpeech: 'noun', definition: 'A small part of something', example: 'Only a fraction of the class had heard of the band.', band: '9-10' },
        { word: 'deteriorate', partOfSpeech: 'verb', definition: 'To slowly get worse or weaker', example: 'The old path had deteriorated, so the council repaved it.', band: '9-10' },
        { word: 'monitor', partOfSpeech: 'verb', definition: 'To watch or check something carefully over time', example: 'The coach monitors how far each runner goes in training.', band: '9-10' },
      ],
      quiz: [
        {
          id: 'q1',
          skill: 'main-idea',
          question: 'What is the main idea of the story?',
          choices: [
            'Museums hide their best art because visitors might damage it',
            'Only a few museums in the world own art',
            'Most museum objects are kept in careful storage, and some museums now let visitors see it',
            'Storage rooms are dusty and forgotten',
          ],
          answerIndex: 2,
          explanation: 'The story explains why most objects are in storage, how they are cared for and how one building lets the public see inside.',
        },
        {
          id: 'q2',
          skill: 'detail',
          question: 'What can happen to old drawings and fabrics if they are exposed to light for too long?',
          choices: ['They can fade', 'They can shrink', 'They become heavier', 'They turn a darker colour'],
          answerIndex: 0,
          explanation: 'The story says they “can fade if they are exposed to light for too long.”',
        },
        {
          id: 'q3',
          skill: 'inference',
          question: 'Why might a museum keep an object in storage even when it has space to show it?',
          choices: [
            'Nobody is allowed to study it',
            'The object is fragile and needs a rest from light',
            'The object is too new to show',
            'Visitors have asked not to see it',
          ],
          answerIndex: 1,
          explanation: 'Fragile works are “shown for a few months and then rested in the dark,” so storage protects them.',
        },
        {
          id: 'q4',
          skill: 'vocabulary',
          question: '“Some items are also fragile.” What does “fragile” mean?',
          choices: ['Very valuable', 'Very old', 'Very large', 'Easily broken or damaged'],
          answerIndex: 3,
          explanation: 'The next sentences explain that these items can fade or be damaged, which is what fragile means.',
        },
        {
          id: 'q5',
          skill: 'purpose',
          question: 'Why does the writer describe the Depot Boijmans Van Beuningen?',
          choices: [
            'To show that all museums are shaped like bowls',
            'To persuade readers to move to Rotterdam',
            'To explain why mirrors damage art',
            'To give an example of a museum sharing its stored collection with visitors',
          ],
          answerIndex: 3,
          explanation: 'It is an example of museums “finding ways to share their hidden collections.”',
        },
      ],
      writingPrompts: [
        {
          id: 'p1',
          kind: 'summary',
          prompt: 'Summarise, in three or four sentences, why museums keep most of their objects in storage.',
          minWords: 40,
          maxWords: 90,
          tips: ['Give at least two reasons.', 'Mention how objects are cared for.', 'Use your own words.'],
        },
        {
          id: 'p2',
          kind: 'letter',
          prompt: 'Write a short letter to a museum asking to see one object from its storage. Explain why it interests you and what you hope to learn.',
          minWords: 60,
          maxWords: 150,
          tips: ['Start with a polite greeting.', 'Describe the object you are curious about.', 'Finish with a clear, polite request.'],
        },
        {
          id: 'p3',
          kind: 'opinion',
          prompt: 'Should museums change their displays often so that more objects are seen, even if visitors sometimes miss their favourites? Give your opinion.',
          minWords: 60,
          maxWords: 150,
          tips: ['State your opinion first.', 'Give one reason from the story.', 'Suggest a way to solve the problem you mention.'],
        },
      ],
      discussion: [
        'If you made a museum of objects from your own life, what would you put on display and what would you keep in storage?',
        'Is it better for a museum to show a few objects in detail or many objects at once? Why?',
      ],
    },
  },
  {
    slug: 'practice-blue-more-than-gold',
    category: 'art',
    title: 'The blue that once cost more than gold',
    excerpt:
      'For centuries, ultramarine blue was made from a rare stone and could cost more than gold. This practice story follows the colour from the mountains of Afghanistan to a chemist’s discovery in the 1820s and a lucky accident in 2009.',
    publishedAt: '2026-01-13T09:00:00.000Z',
    content: {
      keyIdea: 'Ultramarine blue was once so rare and costly that it was worth more than gold, until chemists learned to make it cheaply.',
      levels: {
        '7-8': {
          title: 'The blue that once cost more than gold',
          paragraphs: [
            'Today you can buy a tube of blue paint for a small amount of money. But for hundreds of years, one shade of blue was so precious that it could cost more than gold. It was called ultramarine.',
            'Ultramarine was made from lapis lazuli, a deep blue stone mined in the mountains of what is now Afghanistan. The stone had to be carried a very long way to reach painters in Europe. Its name comes from Latin words meaning “beyond the sea.”',
            'Turning the stone into paint was slow, difficult work. It had to be ground into powder and then carefully washed and kneaded to separate the blue from everything else. Because it was so rare, people who paid for paintings sometimes wrote in their contracts exactly how much ultramarine the artist must use.',
            'Everything changed in the 1820s. A prize was offered in France for anyone who could make ultramarine artificially. A chemist named Jean-Baptiste Guimet found a way, and soon the colour was affordable for everyone.',
            'New blues are still being discovered. In 2009, scientists at Oregon State University created a bright new blue by accident while testing materials for electronics. They called it YInMn blue.',
          ],
        },
        '9-10': {
          title: 'Ultramarine: the story of a precious blue',
          paragraphs: [
            'A tube of blue paint is an ordinary purchase today, but for centuries one particular blue was so scarce and so costly that, weight for weight, it could be worth more than gold. Its name was ultramarine, and its history links remote mountains, Renaissance studios and modern laboratories.',
            'Ultramarine was derived from lapis lazuli, a vivid blue stone mined in the mountains of what is now Afghanistan. The stone travelled vast distances along trade routes before reaching European artists, which is reflected in its name, from the Latin for “beyond the sea.”',
            'Extracting the colour demanded patience. The stone was ground to a fine powder, mixed into a kind of dough and kneaded repeatedly to separate the precious blue particles from the grey minerals around them. Because the result was so valuable, the people who paid for paintings sometimes stated in their contracts precisely how much ultramarine the artist had to use, often reserving it for the robes of the most important figures. The Dutch painter Johannes Vermeer was unusually generous with it.',
            'The stone’s monopoly ended in the 1820s, when a French society offered a prize for a synthetic version. A chemist named Jean-Baptiste Guimet succeeded, and factory-made ultramarine soon made the colour affordable to almost anyone.',
            'The search for new blues continues. In 2009, researchers at Oregon State University accidentally produced a brilliant blue while investigating materials for electronics, a reminder that significant discoveries sometimes emerge from experiments designed for another purpose entirely.',
          ],
        },
      },
      vocabulary: [
        { word: 'precious', partOfSpeech: 'adjective', definition: 'Rare and worth a lot of money, or very important to someone', example: 'That old photo of my grandparents is precious to our family.', band: 'both' },
        { word: 'separate', partOfSpeech: 'verb', definition: 'To divide things or move them apart', example: 'Separate the egg yolks from the whites before you start.', band: 'both' },
        { word: 'affordable', partOfSpeech: 'adjective', definition: 'Cheap enough for people to be able to buy', example: 'The second-hand shop sells affordable bikes for teenagers.', band: 'both' },
        { word: 'rare', partOfSpeech: 'adjective', definition: 'Not common; hard to find', example: 'It is rare to see snow here in April.', band: '7-8' },
        { word: 'discovered', partOfSpeech: 'verb', definition: 'Found for the first time', example: 'We discovered a tiny café hidden behind the station.', band: '7-8' },
        { word: 'scarce', partOfSpeech: 'adjective', definition: 'Hard to get because there is not much of it', example: 'Seats were scarce, so we stood at the back of the hall.', band: '9-10' },
        { word: 'derived', partOfSpeech: 'verb', definition: 'Taken or made from a particular source', example: 'Many English words are derived from French.', band: '9-10' },
        { word: 'synthetic', partOfSpeech: 'adjective', definition: 'Made by people using chemicals, not taken from nature', example: 'My running jacket is made of a light synthetic fabric.', band: '9-10' },
      ],
      quiz: [
        {
          id: 'q1',
          skill: 'main-idea',
          question: 'What is the main idea of the story?',
          choices: [
            'Ultramarine blue was once extremely valuable, until people learned to make it artificially',
            'Gold was once used to make blue paint',
            'Afghanistan is the only place where paint is made',
            'Scientists have stopped looking for new colours',
          ],
          answerIndex: 0,
          explanation: 'The story explains why ultramarine was so costly and how a man-made version in the 1820s made it affordable.',
        },
        {
          id: 'q2',
          skill: 'detail',
          question: 'What was ultramarine made from before the 1820s?',
          choices: ['Crushed blue flowers', 'A blue stone called lapis lazuli', 'Sea water', 'Gold mixed with ink'],
          answerIndex: 1,
          explanation: 'The story says “ultramarine was made from lapis lazuli, a deep blue stone.”',
        },
        {
          id: 'q3',
          skill: 'inference',
          question: 'Why would someone paying for a painting write down how much ultramarine the artist must use?',
          choices: [
            'Because artists usually refused to paint in blue',
            'Because ultramarine was not allowed in Europe',
            'Because it was so expensive that they wanted to be sure it was really used',
            'Because they wanted the painting to look like the sea',
          ],
          answerIndex: 2,
          explanation: 'The story links the contracts to how rare the colour was: “because it was so rare,” buyers wanted to be sure they got it.',
        },
        {
          id: 'q4',
          skill: 'vocabulary',
          question: '“Soon the colour was affordable for everyone.” What does “affordable” mean?',
          choices: ['Easy to see from far away', 'Made in a laboratory', 'Only used in France', 'Cheap enough for people to buy'],
          answerIndex: 3,
          explanation: 'Once it could be made artificially, the colour no longer cost more than gold, so ordinary people could pay for it.',
        },
        {
          id: 'q5',
          skill: 'sequence',
          question: 'Which of these happened most recently?',
          choices: [
            'Jean-Baptiste Guimet found a way to make ultramarine',
            'Scientists at Oregon State University created YInMn blue',
            'A prize was offered in France',
            'Painters in Europe used ultramarine made from stone',
          ],
          answerIndex: 1,
          explanation: 'YInMn blue was created in 2009, long after the prize and Guimet’s discovery in the 1820s.',
        },
      ],
      writingPrompts: [
        {
          id: 'p1',
          kind: 'summary',
          prompt: 'Summarise the story of ultramarine in three or four sentences, from the stone to the paint anyone can buy.',
          minWords: 40,
          maxWords: 90,
          tips: ['Keep the events in order.', 'Explain why it was so expensive.', 'Say what changed in the 1820s.'],
        },
        {
          id: 'p2',
          kind: 'headline',
          prompt: 'Write a headline announcing Jean-Baptiste Guimet’s discovery as if it were news in the 1820s. Add a sentence explaining your word choices.',
          minWords: 15,
          maxWords: 50,
          tips: ['Use a strong verb.', 'Keep the headline under 12 words.', 'Make it exciting but accurate.'],
        },
        {
          id: 'p3',
          kind: 'creative',
          prompt: 'Invent a new colour. Describe what it looks like, what it reminds you of, where you would use it and what you would name it.',
          minWords: 80,
          maxWords: 200,
          tips: ['Compare it with things people already know.', 'Use precise describing words.', 'Explain the reason for its name.'],
        },
      ],
      discussion: [
        'Why do you think people have always been fascinated by rare colours and materials?',
        'YInMn blue was discovered by accident. Can you think of another lucky accident that led to something useful?',
      ],
    },
  },
];
